# Generated by Django 5.1.3 on 2024-11-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_filmovi_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmovi',
            name='slika',
            field=models.ImageField(upload_to='filmovizija'),
        ),
    ]
