# Generated by Django 5.1.3 on 2024-11-14 12:30

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_filmovi_slika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zanrovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zanr', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='filmovi',
            name='dodano',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmovi',
            name='godina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='imdb_ocena',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='link_gledaj',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmovi',
            name='link_preuzmi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmovi',
            name='opis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmovi',
            name='originalni_naslov',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmovi',
            name='preporuceno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmovi',
            name='slika',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='zanrovi',
            field=models.ManyToManyField(related_name='filmovi', to='home.zanrovi'),
        ),
    ]
