# Generated by Django 5.1.3 on 2025-01-31 08:47

import cloudinary.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_zanrovi_filmovi_dodano_filmovi_godina_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmovi',
            name='zanrovi',
        ),
        migrations.AddField(
            model_name='filmovi',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='DomaciFilmovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('godina', models.IntegerField(default=0)),
                ('slika', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('opis', models.TextField()),
                ('dodano', models.DateTimeField(auto_now_add=True)),
                ('preporuceno', models.BooleanField(default=False)),
                ('link_gledaj', models.CharField(max_length=200)),
                ('link_preuzmi', models.CharField(max_length=200)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.DeleteModel(
            name='Zanrovi',
        ),
    ]
