# Generated by Django 5.1.3 on 2025-02-03 09:30

import cloudinary.models
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_domacifilmovi_imdb_ocena_serije_epizoda'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaceSerije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=120)),
                ('slug', models.SlugField(default='')),
                ('imdb_ocena', models.CharField(max_length=120)),
                ('godina', models.CharField(max_length=120)),
                ('slika', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('opis', models.TextField()),
                ('dodano', models.DateTimeField(auto_now_add=True)),
                ('preporuceno', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='DomaciEpizoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epizoda_dodano', models.DateField(auto_now_add=True)),
                ('sezona', models.CharField(blank=True, max_length=120, null=True)),
                ('ep', models.CharField(blank=True, max_length=120, null=True)),
                ('link_gledaj', models.CharField(max_length=200)),
                ('link_preuzmi', models.CharField(max_length=200)),
                ('epizode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.domaceserije')),
            ],
        ),
    ]
