# Generated by Django 5.1.3 on 2025-02-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_domaceserije_domaciepizoda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaciepizoda',
            name='link_gledaj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='domacifilmovi',
            name='link_gledaj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='link_gledaj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filmovi',
            name='link_gledaj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
